version: '3.1'

services:

  mongo:
    image: mongo:4.2.15
    ##restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      #      - ~/docker_data/mongo:/etc/mongo
      - ~/docker_data/mongo/data:/data/db
      - ~/docker_data/mongo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo_web
    ## restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
        #ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
