version: '3'
services:
  consul:
    image: consul
      #    restart: always
    container_name: consul_server
    network_mode: bridge 
    volumes: 
      - ~/docker_data/consul:/tmp/consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 8600:8600/udp
      - 53:53/udp
    command: consul agent -data-dir=/tmp/consul -dev -client=0.0.0.0
